version: '3'

services:
  grpc-server: &grpc-server
    build:
      context: ./python
    image: docker.local/grpc-presentation/grpc-python-server:latest

    working_dir: /usr/local/src
    command: python server.py
    volumes:
      - ./python:/usr/local/src
    user: 1000:1000

  php-client:
    build:
      context: ./php
    image: docker.local/grpc-presentation/grpc-php-client:7.3.2-cli-alpine3.9
    working_dir: /app
    command: php client.php
    volumes:
      - ./php:/app
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=50051
    depends_on:
      - grpc-server
    user: 1000:1000

  python-client:
    <<: *grpc-server
    command: python client.py
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=50051
    depends_on:
      - grpc-server