<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator.proto

namespace Validator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message containing the greetings
 *
 * Generated from protobuf message <code>validator.PINResponse</code>
 */
class PINResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool valid = 1;</code>
     */
    private $valid = false;
    /**
     * Generated from protobuf field <code>string err = 2;</code>
     */
    private $err = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $valid
     *     @type string $err
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Validator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool valid = 1;</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     * Generated from protobuf field <code>bool valid = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @return string
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, True);
        $this->err = $var;

        return $this;
    }

}

