<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator.proto

namespace GPBMetadata;

class Validator
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a0f76616c696461746f722e70726f746f120976616c696461746f" .
            "7222190a0a50494e52657175657374120b0a0370696e1801200128092229" .
            "0a0b50494e526573706f6e7365120d0a0576616c6964180120012808120b" .
            "0a03657272180220012809324b0a0956616c696461746f72123e0a0b5661" .
            "6c696461746550494e12152e76616c696461746f722e50494e5265717565" .
            "73741a162e76616c696461746f722e50494e526573706f6e736522006206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

